# Generated by Django 3.2.8 on 2022-01-03 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
