# Generated by Django 3.2.8 on 2021-10-14 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_rename_employee_employe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employe',
            new_name='Employee',
        ),
    ]
